
import java.awt.Desktop;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CASPER
 */
public class SezarSifrelemeCoz extends javax.swing.JFrame {

    /**
     * Creates new form SezarSifrelemeCoz
     */
    public SezarSifrelemeCoz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCevir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHesgeldiniz = new javax.swing.JLabel();
        lblKaydirmaSayisi = new javax.swing.JLabel();
        txtKaydirmaSayisi = new javax.swing.JTextField();
        lblCozulmusMesaj = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMesaj = new javax.swing.JTextArea();
        btnCevir1 = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();
        lblMesaj = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSifreliMesaj = new javax.swing.JTextArea();
        lblUyari = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnDosya = new javax.swing.JMenu();
        mnKaydet = new javax.swing.JMenuItem();
        mnYardim = new javax.swing.JMenu();
        mnBilgiAl = new javax.swing.JMenuItem();
        mnCikis = new javax.swing.JMenuItem();

        btnCevir.setText("Çevir");
        btnCevir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCevirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sezar Şifre Çözücü");
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblHesgeldiniz.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        lblHesgeldiniz.setText("Sezar Şifrelem Yöntemi İle Şifre Çöz! ");

        lblKaydirmaSayisi.setText("Kaydırma Sayısı Giriniz: ");

        lblCozulmusMesaj.setText("Çözülmüş Mesaj : ");

        txtMesaj.setColumns(20);
        txtMesaj.setRows(5);
        jScrollPane1.setViewportView(txtMesaj);

        btnCevir1.setText("Çevir");
        btnCevir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCevir1ActionPerformed(evt);
            }
        });

        btnGeri.setText("< Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        lblMesaj.setText("Şifreleniş Mesaj :");

        txtSifreliMesaj.setColumns(20);
        txtSifreliMesaj.setRows(5);
        jScrollPane2.setViewportView(txtSifreliMesaj);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMesaj)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCozulmusMesaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGeri)
                        .addGap(18, 18, 18)
                        .addComponent(btnCevir1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHesgeldiniz)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblKaydirmaSayisi)
                        .addGap(18, 18, 18)
                        .addComponent(txtKaydirmaSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(lblUyari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblHesgeldiniz)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKaydirmaSayisi)
                    .addComponent(txtKaydirmaSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUyari))
                .addGap(18, 18, 18)
                .addComponent(lblMesaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCevir1)
                            .addComponent(btnGeri)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCozulmusMesaj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mnDosya.setText("Dosya");

        mnKaydet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnKaydet.setText("Çözülen Metni Kaydet");
        mnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaydetActionPerformed(evt);
            }
        });
        mnDosya.add(mnKaydet);

        jMenuBar1.add(mnDosya);

        mnYardim.setText("Yardim");
        mnYardim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnYardimActionPerformed(evt);
            }
        });

        mnBilgiAl.setText("Bilgi Al");
        mnBilgiAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBilgiAlActionPerformed(evt);
            }
        });
        mnYardim.add(mnBilgiAl);

        mnCikis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnCikis.setText("Çıkış");
        mnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCikisActionPerformed(evt);
            }
        });
        mnYardim.add(mnCikis);

        jMenuBar1.add(mnYardim);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCevirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCevirActionPerformed
        int kaydirmaSayisi = Integer.valueOf(txtKaydirmaSayisi.getText());
        String mesaj = txtMesaj.getText();
        txtSifreliMesaj.setText(sezarCoz(mesaj, kaydirmaSayisi));
    }//GEN-LAST:event_btnCevirActionPerformed

    private void btnCevir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCevir1ActionPerformed
        int kaydirmaSayisi = Integer.valueOf(txtKaydirmaSayisi.getText());
        String mesaj = txtMesaj.getText();
        txtSifreliMesaj.setText(sezarCoz(mesaj, kaydirmaSayisi));
    }//GEN-LAST:event_btnCevir1ActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        Merhaba merhaba = new Merhaba();
        merhaba.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btnGeriActionPerformed

    private void mnBilgiAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBilgiAlActionPerformed
        // Programın çalışır bir videosu browser ile açılır.
        
        String webSite = "https://youtu.be/m5Bf2_439wE";
            Desktop desktop = Desktop.getDesktop();
            
            try {
                desktop.browse(new URI(webSite));
            } catch (IOException ex) {
                lblUyari.setText("URL açılırken bir hata oluştu.");
            } catch (URISyntaxException ex) {
                lblUyari.setText("URL Bulunamadı.");
            }
    }//GEN-LAST:event_mnBilgiAlActionPerformed

    private void mnYardimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnYardimActionPerformed
        
    }//GEN-LAST:event_mnYardimActionPerformed

    private void mnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCikisActionPerformed
        // programdan çıkılmak istendiğinden "emin misiniz?" diye sorar.
        
        Object[] SaveOption = {"Evet", "Hayır"};

        int noSave = JOptionPane.showOptionDialog(null, "Çıkmak İstediğinize emin misiniz?", "Uyarı!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, SaveOption, null);

        if (noSave == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (noSave == JOptionPane.NO_OPTION) {
        }
    }//GEN-LAST:event_mnCikisActionPerformed

    private void mnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaydetActionPerformed
        FileWriter writer = null;
                    try {
                        writer = new FileWriter("sifreliMesaj.txt", true);
                        writer.write(txtSifreliMesaj.getText());
                        
                    } catch (IOException ex) {
                        System.out.println("Dosyaya kaydedilirken bir hata oluştu.");
                    } finally {
                        if (writer != null) {
                            try {
                                writer.close();
                            } catch (IOException ex) {
                                System.out.println("Dosya Kapatılırken bir hata oluştu.");
                            }
                        }
                    }
    }//GEN-LAST:event_mnKaydetActionPerformed

    public String sezarCoz(String metin, int ks) {
        String alfabe = "abcçdefgğhıijklmnoöprsştuüvyz";
        String tersAlfabe = "zyvüutşsrpöonmlkjiıhğgfedçcba";
        metin = metin.toLowerCase();
        String sifreliMesaj = "";
        char bosluk = ' ';
        int kaydir;

        for (int i = 0; i < metin.length(); i++) {
            if (metin.charAt(i) == bosluk) {
                sifreliMesaj += bosluk;
            } else if (metin.charAt(i) == '.') {
                sifreliMesaj += '.';
            } else {
                for (int j = 0; j < 29; j++) {
                    if (metin.charAt(i) == alfabe.charAt(j)) {
                        if(j < ks){
                            sifreliMesaj += tersAlfabe.charAt(((j + ks) % 29)-1);
                        }else{
                            sifreliMesaj += alfabe.charAt((j - ks) % 29);
                        }
                    }
                }
            }
        }
        return sifreliMesaj;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SezarSifrelemeCoz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SezarSifrelemeCoz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SezarSifrelemeCoz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SezarSifrelemeCoz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SezarSifrelemeCoz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCevir;
    private javax.swing.JButton btnCevir1;
    private javax.swing.JButton btnGeri;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCozulmusMesaj;
    private javax.swing.JLabel lblHesgeldiniz;
    private javax.swing.JLabel lblKaydirmaSayisi;
    private javax.swing.JLabel lblMesaj;
    private javax.swing.JLabel lblUyari;
    private javax.swing.JMenuItem mnBilgiAl;
    private javax.swing.JMenuItem mnCikis;
    private javax.swing.JMenu mnDosya;
    private javax.swing.JMenuItem mnKaydet;
    private javax.swing.JMenu mnYardim;
    private javax.swing.JTextField txtKaydirmaSayisi;
    private javax.swing.JTextArea txtMesaj;
    private javax.swing.JTextArea txtSifreliMesaj;
    // End of variables declaration//GEN-END:variables
}
